_wandb:
    value:
        cli_version: 0.18.6
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.18.6
            "8":
                - 5
            "12": 0.18.6
            "13": linux-x86_64
batch_size:
    value: 32
learning_rate:
    value: 0.001
n_components:
    value: 5
ridge_alpha:
    value: 1
